var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/stories/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ec-t3t._.js")
R.c("server/chunks/ssr/_0qi5kg1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0fv.~-i.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y~gs73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/_0seic6l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_stories_page_actions_0smzj24.js")
R.m(12442)
module.exports=R.m(12442).exports
